col removeAction 1;
saveGame;
playSound "briefing2";
hint "Great Job, Lieutenant. We are showing the wide band data transmissions have ceased. The base CSAT hijacked is in lockdown. It's going to be a tough job getting in there to find out what is going on. Luckily, we have a secret agent that has infiltrated the facility under the cover of a lab inspector.";
sleep 16.0;
hint "You are to move to his location and provide exfiltration support once he completes his objectives.";
sleep 3.0;
RTB setTaskState "Succeeded";
titleText ["Secret Agent Rick Phillips - Cover: Lab Inspector for CSAT Operations Management", "BLACK FADED", 0.5];
lt setPosATL [17436.7,13933.1,0];  
medic setPosATL [17436.7,13933.0,0];  
comms setPosATL [17436.7,13933.2,0];  
demo setPosATL [17436.7,13933.3,0];  
scout setPosATL [17436.7,13933.4,0];
selectPlayer scientist; 
lab1 = scientist createSimpleTask ["Infiltrate the Lab. Obtain the Data."];
lab1 setSimpleTaskDescription ["Infiltrate the Lab utilizing your cover as a lab inspector, locate evidence of the activity there.","Infiltrate the Lab","Infiltrate the Lab"];
lab1 setSimpleTaskDestination (getMarkerPos "lab1");
lab1 setTaskState "Assigned";
scientist setCurrentTask lab1;
hint "Move to the laboratory without drawing attention to yourself. Obtain the data and transmit it to NATO Command.";
playSound "techtheme3";
