hint "USB Key Inserted. Please Stand By. Uploading...";
laptop removeAction 0;
sleep 1.0;
titleText ["Uploading....10", "PLAIN", 0.3];
sleep 1.0;
titleText ["Uploading....9", "PLAIN", 0.3];
sleep 1.0;
titleText ["Uploading....8", "PLAIN", 0.3];
sleep 1.0;
titleText ["Uploading....7", "PLAIN", 0.3];
sleep 1.0;
titleText ["Uploading....6", "PLAIN", 0.3];
sleep 1.0; 
titleText ["Uploading....5", "PLAIN", 0.3];
sleep 1.0;
titleText ["Uploading....4", "PLAIN", 0.3];
sleep 1.0;
titleText ["Uploading....3", "PLAIN", 0.3];
sleep 1.0;
titleText ["Uploading....2", "PLAIN", 0.3];
sleep 1.0;
titleText ["Uploading....1", "PLAIN", 0.3];
sleep 1.0;
titleText ["Transmitting Data to Command...Standby...", "PLAIN", 0.3];
sleep 5.0;
titleText ["Trojan Horse Infection Complete.", "PLAIN", 0.3];
sleep 3.0;
hint "The trojan horse virus has been uploaded.";
sleep 3.0;
laptop setDamage 1;